// Copyright 08-Dec-2021 ºDeme
// GNU General Public License - V3 <http://www.gnu.org/licenses/>

#include "dmc/char/Lchar.h"

Lchar *lchar_new(void) {
  return (Lchar *)list_new();
}

int lchar_size(Lchar *this) {
  return list_size((List *)this);
}

Lchar *lchar_tail(Lchar *this) {
  return (Lchar *)list_tail((List *)this);
}

char *lchar_head (Lchar *this) {
  return list_head((List *)this);
}

Ochar *lchar_get (Lchar *this, int ix) {
  return (Ochar *)list_get((List *)this, ix);
}

int lchar_empty(Lchar *this) {
  return list_empty((List *)this);
}

Lchar *lchar_cons(Lchar *this, char *o) {
  return (Lchar *)list_cons((List *)this, o);
}

Lchar *lchar_cat(Lchar *this, Lchar *l) {
  return (Lchar *)list_cat((List *)this, (List *)l);
}

Lchar *lchar_reverse(Lchar *this) {
  return (Lchar *)list_reverse((List *)this);
}

Lchar *lchar_sort (Lchar *this, int (*greater)(char *e1, char *e2)) {
  return (Lchar *)list_sort((List *)this, (int(*)(void *, void *))greater);
}

int lchar_all (Lchar *this, int (*pred)(char *e)) {
  return list_all((List *)this, (int(*)(void *))pred);
}

int lchar_any (Lchar *this, int (*pred)(char *e)) {
  return list_any((List *)this, (int(*)(void *))pred);
}

int lchar_index (Lchar *this, int (*pred)(char *e)) {
  return list_index((List *)this, (int(*)(void *))pred);
}

int lchar_last_index (Lchar *this, int (*pred)(char *e)) {
  return list_last_index((List *)this, (int(*)(void *))pred);
}

Ochar *lchar_find(Lchar *this, int (*pred)(char *e)) {
  return (Ochar *)list_find((List *)this, (int(*)(void *))pred);
}

Ochar *lchar_find_last(Lchar *this, int (*pred)(char *e)) {
  return (Ochar *)list_find_last((List *)this, (int(*)(void *))pred);
}

Lchar *lchar_filter (Lchar *this, int (*pred)(char *e)) {
  return (Lchar *)list_filter((List *)this, (int(*)(void *))pred);
}

Lchar *lchar_take (Lchar *this, int n) {
  return (Lchar *)list_take((List *)this, n);
}

Lchar *lchar_takef (Lchar *this, int (*pred)(char *e)) {
  return (Lchar *)list_takef((List *)this, (int(*)(void *))pred);
}

Lchar *lchar_drop (Lchar *this, int n) {
  return (Lchar *)list_drop((List *)this, n);
}

Lchar *lchar_dropf (Lchar *this, int (*pred)(char *e)) {
  return (Lchar *)list_dropf((List *)this, (int(*)(void *))pred);
}

/// Returns a new List with elements generated by converter.
List *lchar_map (Lchar *this, void *(*converter)(char *e)) {
  return list_map((List *)this, (void *(*)(void *))converter);
}

List *lchar_map2 (Lchar *this, void *(*conv1)(char *e), void *(*conv2)(char *e)) {
  return list_map2((List *)this, (void *(*)(void *))conv1, (void *(*)(void *))conv2);
}

List *lchar_zip (Lchar *l1, Lchar *l2, void *(*converter)(char *e1, char *e2)) {
  return list_zip((List *)l1, (List *)l2, (void *(*)(void *, void *))converter);
}

List *lchar_zip3 (
  Lchar *l1, Lchar *l2, Lchar *l3,
  void *(*converter)(char *e1, char *e2, char *e3)
) {
  return list_zip3(
    (List *)l1, (List *)l2, (List *)l3,
    (void *(*)(void *, void *, void *))converter
  );
}

Achar *lchar_to_arr (Lchar *this) {
  return (Achar *)list_to_arr((List *)this);
}

Lchar *lchar_from_arr (Achar *a) {
  return (Lchar *)list_from_arr((Arr *) a);
}

char *lchar_to_js(Lchar *this, char *(*to)(char *)) {
  return list_to_js((List *) this, (char *(*)(void *))to);
}

Lchar *lchar_from_js(char *js, char *(*from)(char *)) {
  return (Lchar *)list_from_js(js, (void *(*)(char *))from);
}

//--// Not remove

