// Copyright 08-Dec-2021 ºDeme
// GNU General Public License - V3 <http://www.gnu.org/licenses/>

#include "dmc/char/LKchar.h"

LKchar *lKchar_new(void) {
  return (LKchar *)list_new();
}

int lKchar_size(LKchar *this) {
  return list_size((List *)this);
}

LKchar *lKchar_tail(LKchar *this) {
  return (LKchar *)list_tail((List *)this);
}

Kchar *lKchar_head (LKchar *this) {
  return list_head((List *)this);
}

OKchar *lKchar_get (LKchar *this, int ix) {
  return (OKchar *)list_get((List *)this, ix);
}

int lKchar_empty(LKchar *this) {
  return list_empty((List *)this);
}

LKchar *lKchar_cons(LKchar *this, Kchar *o) {
  return (LKchar *)list_cons((List *)this, o);
}

LKchar *lKchar_cat(LKchar *this, LKchar *l) {
  return (LKchar *)list_cat((List *)this, (List *)l);
}

LKchar *lKchar_reverse(LKchar *this) {
  return (LKchar *)list_reverse((List *)this);
}

LKchar *lKchar_sort (LKchar *this, int (*greater)(Kchar *e1, Kchar *e2)) {
  return (LKchar *)list_sort((List *)this, (int(*)(void *, void *))greater);
}

int lKchar_all (LKchar *this, int (*pred)(Kchar *e)) {
  return list_all((List *)this, (int(*)(void *))pred);
}

int lKchar_any (LKchar *this, int (*pred)(Kchar *e)) {
  return list_any((List *)this, (int(*)(void *))pred);
}

int lKchar_index (LKchar *this, int (*pred)(Kchar *e)) {
  return list_index((List *)this, (int(*)(void *))pred);
}

int lKchar_last_index (LKchar *this, int (*pred)(Kchar *e)) {
  return list_last_index((List *)this, (int(*)(void *))pred);
}

OKchar *lKchar_find(LKchar *this, int (*pred)(Kchar *e)) {
  return (OKchar *)list_find((List *)this, (int(*)(void *))pred);
}

OKchar *lKchar_find_last(LKchar *this, int (*pred)(Kchar *e)) {
  return (OKchar *)list_find_last((List *)this, (int(*)(void *))pred);
}

LKchar *lKchar_filter (LKchar *this, int (*pred)(Kchar *e)) {
  return (LKchar *)list_filter((List *)this, (int(*)(void *))pred);
}

LKchar *lKchar_take (LKchar *this, int n) {
  return (LKchar *)list_take((List *)this, n);
}

LKchar *lKchar_takef (LKchar *this, int (*pred)(Kchar *e)) {
  return (LKchar *)list_takef((List *)this, (int(*)(void *))pred);
}

LKchar *lKchar_drop (LKchar *this, int n) {
  return (LKchar *)list_drop((List *)this, n);
}

LKchar *lKchar_dropf (LKchar *this, int (*pred)(Kchar *e)) {
  return (LKchar *)list_dropf((List *)this, (int(*)(void *))pred);
}

/// Returns a new List with elements generated by converter.
List *lKchar_map (LKchar *this, void *(*converter)(Kchar *e)) {
  return list_map((List *)this, (void *(*)(void *))converter);
}

List *lKchar_map2 (LKchar *this, void *(*conv1)(Kchar *e), void *(*conv2)(Kchar *e)) {
  return list_map2((List *)this, (void *(*)(void *))conv1, (void *(*)(void *))conv2);
}

List *lKchar_zip (LKchar *l1, LKchar *l2, void *(*converter)(Kchar *e1, Kchar *e2)) {
  return list_zip((List *)l1, (List *)l2, (void *(*)(void *, void *))converter);
}

List *lKchar_zip3 (
  LKchar *l1, LKchar *l2, LKchar *l3,
  void *(*converter)(Kchar *e1, Kchar *e2, Kchar *e3)
) {
  return list_zip3(
    (List *)l1, (List *)l2, (List *)l3,
    (void *(*)(void *, void *, void *))converter
  );
}

AKchar *lKchar_to_arr (LKchar *this) {
  return (AKchar *)list_to_arr((List *)this);
}

LKchar *lKchar_from_arr (AKchar *a) {
  return (LKchar *)list_from_arr((Arr *) a);
}

char *lKchar_to_js(LKchar *this, char *(*to)(Kchar *)) {
  return list_to_js((List *) this, (char *(*)(void *))to);
}

LKchar *lKchar_from_js(char *js, Kchar *(*from)(char *)) {
  return (LKchar *)list_from_js(js, (void *(*)(char *))from);
}

//--// Not remove

