// Copyright 08-Dec-2021 ºDeme
// GNU General Public License - V3 <http://www.gnu.org/licenses/>

#include "dmc/Kv/LKv.h"

LKv *lKv_new(void) {
  return (LKv *)list_new();
}

int lKv_size(LKv *this) {
  return list_size((List *)this);
}

LKv *lKv_tail(LKv *this) {
  return (LKv *)list_tail((List *)this);
}

Kv *lKv_head (LKv *this) {
  return list_head((List *)this);
}

OKv *lKv_get (LKv *this, int ix) {
  return (OKv *)list_get((List *)this, ix);
}

int lKv_empty(LKv *this) {
  return list_empty((List *)this);
}

LKv *lKv_cons(LKv *this, Kv *o) {
  return (LKv *)list_cons((List *)this, o);
}

LKv *lKv_cat(LKv *this, LKv *l) {
  return (LKv *)list_cat((List *)this, (List *)l);
}

LKv *lKv_reverse(LKv *this) {
  return (LKv *)list_reverse((List *)this);
}

LKv *lKv_sort (LKv *this, int (*greater)(Kv *e1, Kv *e2)) {
  return (LKv *)list_sort((List *)this, (int(*)(void *, void *))greater);
}

int lKv_all (LKv *this, int (*pred)(Kv *e)) {
  return list_all((List *)this, (int(*)(void *))pred);
}

int lKv_any (LKv *this, int (*pred)(Kv *e)) {
  return list_any((List *)this, (int(*)(void *))pred);
}

int lKv_index (LKv *this, int (*pred)(Kv *e)) {
  return list_index((List *)this, (int(*)(void *))pred);
}

int lKv_last_index (LKv *this, int (*pred)(Kv *e)) {
  return list_last_index((List *)this, (int(*)(void *))pred);
}

OKv *lKv_find(LKv *this, int (*pred)(Kv *e)) {
  return (OKv *)list_find((List *)this, (int(*)(void *))pred);
}

OKv *lKv_find_last(LKv *this, int (*pred)(Kv *e)) {
  return (OKv *)list_find_last((List *)this, (int(*)(void *))pred);
}

LKv *lKv_filter (LKv *this, int (*pred)(Kv *e)) {
  return (LKv *)list_filter((List *)this, (int(*)(void *))pred);
}

LKv *lKv_take (LKv *this, int n) {
  return (LKv *)list_take((List *)this, n);
}

LKv *lKv_takef (LKv *this, int (*pred)(Kv *e)) {
  return (LKv *)list_takef((List *)this, (int(*)(void *))pred);
}

LKv *lKv_drop (LKv *this, int n) {
  return (LKv *)list_drop((List *)this, n);
}

LKv *lKv_dropf (LKv *this, int (*pred)(Kv *e)) {
  return (LKv *)list_dropf((List *)this, (int(*)(void *))pred);
}

/// Returns a new List with elements generated by converter.
List *lKv_map (LKv *this, void *(*converter)(Kv *e)) {
  return list_map((List *)this, (void *(*)(void *))converter);
}

List *lKv_map2 (LKv *this, void *(*conv1)(Kv *e), void *(*conv2)(Kv *e)) {
  return list_map2((List *)this, (void *(*)(void *))conv1, (void *(*)(void *))conv2);
}

List *lKv_zip (LKv *l1, LKv *l2, void *(*converter)(Kv *e1, Kv *e2)) {
  return list_zip((List *)l1, (List *)l2, (void *(*)(void *, void *))converter);
}

List *lKv_zip3 (
  LKv *l1, LKv *l2, LKv *l3,
  void *(*converter)(Kv *e1, Kv *e2, Kv *e3)
) {
  return list_zip3(
    (List *)l1, (List *)l2, (List *)l3,
    (void *(*)(void *, void *, void *))converter
  );
}

AKv *lKv_to_arr (LKv *this) {
  return (AKv *)list_to_arr((List *)this);
}

LKv *lKv_from_arr (AKv *a) {
  return (LKv *)list_from_arr((Arr *) a);
}

char *lKv_to_js(LKv *this, char *(*to)(Kv *)) {
  return list_to_js((List *) this, (char *(*)(void *))to);
}

LKv *lKv_from_js(char *js, Kv *(*from)(char *)) {
  return (LKv *)list_from_js(js, (void *(*)(char *))from);
}

//--// Not remove

